version: "3.7"

services:
  app:
    build: 
      context: .  # Der Build-Kontext ist das aktuelle Verzeichnis
      dockerfile: Dockerfile  # Dockerfile wird hier angegeben
    container_name: einkaufsliste-app
    ports:
      - "80:80"  # Mappt den Nginx-Port 80 im Container auf Port 80 des Hosts
    environment:
      - NODE_ENV=development  # Setzt die Umgebungsvariable für die Entwicklung
    volumes:
      - ./src:/usr/src/docker/ki-app  # Bindet den Quellcode an den Container
      - ./docker/nginx.conf:/etc/nginx/nginx.conf  # Nginx-Konfiguration wird geladen
    restart: always  # Container wird bei Fehler automatisch neu gestartet
